Why is NumPy faster than lists?
1) We can specify how many byte of integer to store and read. Lists store a lot more information.
2) NumPy does not type check when iterating through objects.
3) NumPy uses contiguous memory when storing values therefore - We can utilize SIMD Vector processing, Effective cache utilization.
4) NumPy gives a lot more functionalities.
Advantages of NumPy
1) MATLAB replacement
2) Plotting (MatPlotLib)
3) Backend (Pandas, Connect4, Digital Photography)
4) Machine Learning

In [1]:
import numpy as np

In [21]:
#creating arrays
a = np.array([1,2,4], dtype = 'int8')
print(a)

[1 2 4]


In [17]:
b = np.array([[1,2,3.4],[5,2,3]])
print(b)

[[1.  2.  3.4]
 [5.  2.  3. ]]


In [6]:
c = np.array([[1,2,3],[1,2]])
print(c)

[list([1, 2, 3]) list([1, 2])]


In [11]:
#Getting dimension
b.ndim

2

In [14]:
#get shape
c.shape

(2,)

In [29]:
#get Type
b.dtype

dtype('float64')

In [30]:
#get size - number of bytes each value takes
b.itemsize

8

In [28]:
#get total size of bytes
b.nbytes

48

In [33]:
#Array Manipulation
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [35]:
arr[:,:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [37]:
arr[0,:]

array([1, 2, 3, 4, 5, 6])

In [40]:
arr[:,0]

array([1, 7])

In [42]:
#Numpy also allows negative indexing
arr[1,-2]

11

In [45]:
#Slicing
arr[:,1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [47]:
arr[0,0] = 60
arr

array([[60,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
arr[0,1:4]=[2,3,4]
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [54]:
#Initializing arrays

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones(3)

array([1., 1., 1.])

In [61]:
np.full((2,2),6 , dtype='int8')

array([[6, 6],
       [6, 6]], dtype=int8)

In [66]:
np.random.rand(4,2)

array([[0.34805464, 0.87276342],
       [0.22483704, 0.45897239],
       [0.42162431, 0.6082192 ],
       [0.23338685, 0.12464605]])

In [72]:
np.random.randint(-100,100,size=(3,3))

array([[-71,  44, -82],
       [-81,  35,   0],
       [ 98, -33,  91]])

In [73]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
prac = np.ones((5,5))
prac[1:4,1:4] = 0
prac[2,2] = 9
print(prac)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [78]:
#Copying arrays. Directly assigning variables creates a reference so use copy() function

In [81]:
a1=np.array([1,2,3])
a2=a1.copy()
a2[0]=100
print(a1)
print(a2)

[1 2 3]
[100   2   3]


In [82]:
#We can directly perform arithmetic and trig funtions to entire array

In [84]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [86]:
#Reshaping arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [96]:
#Loading data from file 
file = np.genfromtxt('data.txt',delimiter=',')
file = file.astype('int8')
file

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int8)